name: ROS 2 Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.7.7
      with:
        use-ros2-testing: true  # Utilizza i pacchetti di test ROS 2
        install-connext: true    # Installa il middleware Connext
        required-ros-distributions: "humble"  # Specifica le distribuzioni ROS 2 richieste

    - name: Install dependencies
      run: |
        sudo apt-get update && rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro humble -y

    - name: Build with colcon
      run: colcon build --packages-select uclv_rh8d_ros2_tests  # Sostituisci <package_to_build> con il nome del tuo pacchetto ROS 2
