name: ROS 2 Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Pull Docker image from Docker Hub
    - name: Pull Docker image
      run: docker pull robertochello/my-ros2-env:latest
    
    # Run Docker container with ROS 2 environment
    - name: Run Docker container
      run: docker run --rm -v $PWD:/workspace -w /workspace robertochello/my-ros2-env bash -c "source /opt/ros/humble/setup.bash && colcon build --packages-select uclv_rh8d_ros2_tests"
