name: ROS 2 Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Build Docker image
    - name: Build Docker image
      run: docker build -t my-ros2-env -f Dockerfile .
    
    # Run Docker container with ROS 2 environment
    - name: Run Docker container
      run: docker run --rm -v $PWD:/workspace -w /workspace my-ros2-env bash -c "source /opt/ros/humble/setup.bash && colcon build --packages-select uclv_rh8d_ros2_tests"
